/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ticket;

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    
    @Test void placeholder() {
    
    }
}
