/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ticket;

import org.junit.jupiter.api.*;

import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.*;

class CinemaTest {

    @Test void basicTest() {
        Cinema c = new Cinema("Cool Dude Cinema", 1, 1, 1, 1);
        assertEquals(c.getCinemaID(), 1);
        assertEquals(c.getCinemaName(), "Cool Dude Cinema");
    }

    @Test
    void getCinemaTest(){
        Cinema c1 = new Cinema("Cool Dude Cinema", 1, 1, 1, 1);
        Cinema c2 = new Cinema("Cool Dude Cinema", 2, 1, 1, 1);
        Cinema c3 = new Cinema("Cool Dude Cinema", 3, 1, 1, 1);

        ArrayList<Cinema> cList = new ArrayList<>();
        cList.add(c1);
        cList.add(c2);
        cList.add(c3);
        assertEquals(c1, Cinema.getCinemaWithID(cList, 1));

    }

    @Test void testGetPriceList() {
        final double[] priceG = {15, 25, 30, 20};
        final double[] priceS = {13, 23, 28, 18};
        final double[] priceB = {10, 20, 25, 15};
        assertArrayEquals(priceG, Cinema.ScreenType.GOLD.getPriceList());
        assertArrayEquals(priceS, Cinema.ScreenType.SILVER.getPriceList());
        assertArrayEquals(priceB, Cinema.ScreenType.BRONZE.getPriceList());
    }
}
