/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ticket;

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;

class MovieTest {

    @Test void basicFunctionality() {
        Movie m = new Movie("General", "Movie Name", 120, 1, "A fridge too far", "1900-12-14 10:45", "Joel", new String[]{"Joel", "Also Joel"});
        assertEquals(m.getRating(), Movie.Rating.GENERAL);
        assertEquals(m.getID(), 1);
        assertEquals(m.getSynopsis(), "A fridge too far");
        assertEquals(m.getName(), "Movie Name");
        assertEquals(m.getDirector(), "Joel");
        assertEquals(m.getDuration(), 120);
        assertEquals(m.getRelease(), "1900-12-14 10:45");
    }

    @Test
    void getRatingTest(){
        Movie m1 = new Movie("General", "Movie Name", 120, 1, "A fridge too far", "1900-12-14 10:45", "Joel", new String[]{"Joel", "Also Joel"});
        Movie m2 = new Movie("Parental_guidance", "Movie Name", 120, 1, "A fridge too far", "1900-12-14 10:45", "Joel", new String[]{"Joel", "Also Joel"});
        Movie m3 = new Movie("mature", "Movie Name", 120, 1, "A fridge too far", "1900-12-14 10:45", "Joel", new String[]{"Joel", "Also Joel"});
        Movie m4 = new Movie("mature_accompanies", "Movie Name", 120, 1, "A fridge too far", "1900-12-14 10:45", "Joel", new String[]{"Joel", "Also Joel"});
        Movie m5 = new Movie("restricted", "Movie Name", 120, 1, "A fridge too far", "1900-12-14 10:45", "Joel", new String[]{"Joel", "Also Joel"});
        Movie m6 = new Movie("jibberish", "Movie Name", 120, 1, "A fridge too far", "1900-12-14 10:45", "Joel", new String[]{"Joel", "Also Joel"});

        assertEquals(Movie.Rating.GENERAL, m1.getRating());
        assertEquals(Movie.Rating.PARENTAL_GUIDANCE, m2.getRating());
        assertEquals(Movie.Rating.MATURE, m3.getRating());
        assertEquals(Movie.Rating.MATURE_ACCOMPANIES, m4.getRating());
        assertEquals(Movie.Rating.RESTRICTED, m5.getRating());
        assertEquals(Movie.Rating.RESTRICTED, m6.getRating());
    }
}
